from __future__ import annotations

import argparse
import inspect
import json
import os
import random
import time
from contextlib import nullcontext
from copy import deepcopy
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms.functional as TF
from PIL import Image, ImageOps
from scipy.ndimage import gaussian_filter
from torch.utils.data import DataLoader, Dataset
from torch.cuda.amp import GradScaler, autocast
from torchvision.transforms import InterpolationMode, Normalize, ToTensor
from tqdm.auto import tqdm

import VisualAD_lib
from utils.anomaly_detection import generate_anomaly_map_from_tokens
from utils.feature_transform import create_feature_transform
from utils.loss import ContrastiveLoss
from utils.scoring import DEFAULT_TOPK_RATIO, reduce_anomaly_map
from VisualAD_lib.constants import OPENAI_DATASET_MEAN, OPENAI_DATASET_STD


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Finetune the pretrained VisualAD checkpoint on bottle-cap images using "
            "image-level anomaly labels only. This supports the current anomaly-only own_datasets setup."
        )
    )
    parser.add_argument(
        "--metadata-path",
        type=Path,
        default=Path("prepared_data/bottle_positive_only/split.json"),
        help="Metadata json generated by scripts/prepare_bottle_finetune_data.py",
    )
    parser.add_argument(
        "--checkpoint-path",
        type=Path,
        default=Path("weight/train_on_mvtec/CLIP.pth"),
        help="Pretrained VisualAD checkpoint to finetune from.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("runs/bottle_positive_only"),
        help="Directory to save finetuned checkpoints and logs.",
    )
    parser.add_argument("--requested-device", type=str, default="cuda:0", help="'auto', 'cpu', or 'cuda:0'.")
    parser.add_argument("--epochs", type=int, default=12, help="Number of finetuning epochs.")
    parser.add_argument("--batch-size", type=int, default=4, help="Training batch size.")
    parser.add_argument(
        "--num-workers",
        type=int,
        default=min(8, max(0, (os.cpu_count() or 1) // 2)),
        help="DataLoader worker count. Ignored when --cache-images is enabled.",
    )
    parser.add_argument(
        "--cache-images",
        action="store_true",
        default=True,
        help="Preprocess and cache all images in CPU memory once before training to reduce loader bottlenecks.",
    )
    parser.add_argument(
        "--no-cache-images",
        action="store_false",
        dest="cache_images",
        help="Disable image caching and load images on the fly.",
    )
    parser.add_argument(
        "--cache-dtype",
        type=str,
        default="float16",
        choices=["float16", "float32"],
        help="Storage dtype used for cached images.",
    )
    parser.add_argument(
        "--prefetch-factor",
        type=int,
        default=2,
        help="DataLoader prefetch factor when num_workers > 0.",
    )
    parser.add_argument(
        "--disable-amp",
        action="store_true",
        help="Disable CUDA mixed precision training.",
    )
    parser.add_argument("--learning-rate", type=float, default=1e-4, help="Optimizer learning rate.")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="Optimizer weight decay.")
    parser.add_argument("--sigma", type=float, default=4.0, help="Gaussian sigma used for validation-style evaluation.")
    parser.add_argument(
        "--decision-threshold",
        type=float,
        default=0.0,
        help="Image-level anomaly decision threshold. This matches the project default.",
    )
    parser.add_argument(
        "--positive-margin",
        type=float,
        default=1.0,
        help="Margin target for anomaly scores on positive samples.",
    )
    parser.add_argument(
        "--margin-loss-weight",
        type=float,
        default=0.5,
        help="Weight for the score margin loss.",
    )
    parser.add_argument(
        "--anchor-loss-weight",
        type=float,
        default=1e-4,
        help="Weight for anchoring trainable parameters to the pretrained checkpoint.",
    )
    parser.add_argument(
        "--token-relation-weight",
        type=float,
        default=0.05,
        help="Weight for keeping anomaly/normal token features separated.",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed.")
    parser.add_argument(
        "--max-train-steps",
        type=int,
        default=0,
        help="Optional cap on steps per epoch for smoke testing. 0 means full epoch.",
    )
    parser.add_argument(
        "--max-val-steps",
        type=int,
        default=0,
        help="Optional cap on validation steps for smoke testing. 0 means full validation.",
    )
    return parser.parse_args()


def resolve_project_root() -> Path:
    return Path(__file__).resolve().parent


def resolve_path(project_root: Path, path: Path) -> Path:
    return path if path.is_absolute() else project_root / path


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def resolve_device(requested_device: str) -> str:
    if requested_device == "auto":
        return "cuda:0" if torch.cuda.is_available() else "cpu"
    return requested_device


def ensure_real_checkpoint(path: Path):
    prefix = path.read_bytes()[:128]
    if prefix.startswith(b"version https://git-lfs.github.com/spec/v1"):
        raise RuntimeError(
            "Checkpoint is still a Git LFS pointer. Please download the real checkpoint before finetuning."
        )


def torch_load_compat(path, map_location="cpu"):
    signature = inspect.signature(torch.load)
    if "weights_only" in signature.parameters:
        return torch.load(path, map_location=map_location, weights_only=False)
    return torch.load(path, map_location=map_location)


def clip_mean_fill_rgb():
    return tuple(int(round(channel * 255)) for channel in OPENAI_DATASET_MEAN)


def pad_short_side_to_square(image: Image.Image, fill_rgb=None):
    if fill_rgb is None:
        fill_rgb = clip_mean_fill_rgb()

    width, height = image.size
    side = max(width, height)
    pad_left = (side - width) // 2
    pad_top = (side - height) // 2
    pad_right = side - width - pad_left
    pad_bottom = side - height - pad_top

    padded = ImageOps.expand(
        image,
        border=(pad_left, pad_top, pad_right, pad_bottom),
        fill=fill_rgb,
    )
    return padded


def get_cache_dtype(name: str):
    return torch.float16 if name == "float16" else torch.float32


def preprocess_image_for_visualad(image_path: Path, image_size: int) -> torch.Tensor:
    image_pil = Image.open(image_path).convert("RGB")
    padded_pil = pad_short_side_to_square(image_pil, fill_rgb=clip_mean_fill_rgb())
    resized_pil = TF.resize(padded_pil, [image_size, image_size], interpolation=InterpolationMode.BICUBIC)

    tensor = ToTensor()(resized_pil)
    tensor = Normalize(OPENAI_DATASET_MEAN, OPENAI_DATASET_STD)(tensor)
    return tensor


class BottleBinaryDataset(Dataset):
    def __init__(
        self,
        entries: List[Dict],
        image_size: int,
        cache_images: bool = True,
        cache_dtype: str = "float16",
        desc: str = "dataset",
    ):
        self.entries = entries
        self.image_size = image_size
        self.cache_images = cache_images
        self.cache_dtype = get_cache_dtype(cache_dtype)
        self.cached_items = None

        if self.cache_images:
            self.cached_items = []
            progress = tqdm(self.entries, desc=f"Caching {desc}", leave=False, mininterval=5.0)
            for item in progress:
                image_path = Path(item["path"])
                image_tensor = preprocess_image_for_visualad(image_path, self.image_size)
                self.cached_items.append(
                    {
                        "image": image_tensor.to(dtype=self.cache_dtype).contiguous(),
                        "label": float(item["label"]),
                        "path": str(image_path),
                        "source_name": item.get("source_name", "unknown"),
                        "defect_type": item.get("defect_type", "unknown"),
                    }
                )

    def __len__(self):
        return len(self.entries)

    def __getitem__(self, index):
        if self.cached_items is not None:
            cached = self.cached_items[index]
            image_tensor = cached["image"].float()
            label = torch.tensor(cached["label"], dtype=torch.float32)
            return {
                "image": image_tensor,
                "label": label,
                "path": cached["path"],
                "source_name": cached["source_name"],
                "defect_type": cached["defect_type"],
            }

        item = self.entries[index]
        image_path = Path(item["path"])
        image_tensor = preprocess_image_for_visualad(image_path, self.image_size)
        label = torch.tensor(float(item["label"]), dtype=torch.float32)
        return {
            "image": image_tensor,
            "label": label,
            "path": str(image_path),
            "source_name": item.get("source_name", "unknown"),
            "defect_type": item.get("defect_type", "unknown"),
        }


def load_metadata(metadata_path: Path):
    payload = json.loads(metadata_path.read_text())
    return payload["train"], payload["val"], payload.get("stats", {})


def freeze_backbone_except_tokens(model: nn.Module):
    for parameter in model.parameters():
        parameter.requires_grad = False
    model.visual.anomaly_token.requires_grad_(True)
    model.visual.normal_token.requires_grad_(True)


def load_visualad_bundle(checkpoint_path: Path, device: str):
    ensure_real_checkpoint(checkpoint_path)

    checkpoint = torch_load_compat(str(checkpoint_path), map_location=device)
    backbone = checkpoint.get("backbone", "ViT-L/14@336px")
    image_size = int(checkpoint.get("image_size", 518))
    features_list = checkpoint.get("features_list", [6, 12, 18, 24])

    model, _ = VisualAD_lib.load(backbone, device=device)
    model.to(device)
    model.eval()

    freeze_backbone_except_tokens(model)

    feature_dim = model.visual.embed_dim
    model.visual.anomaly_token.data = checkpoint["anomaly_token"].to(device)
    model.visual.normal_token.data = checkpoint["normal_token"].to(device)

    layer_transforms = nn.ModuleDict()
    if "layer_transforms" in checkpoint:
        for layer_name, state_dict in checkpoint["layer_transforms"].items():
            hidden_dim = state_dict["mlp.0.weight"].shape[0]
            module = create_feature_transform(
                transform_type="mlp",
                input_dim=feature_dim,
                hidden_dim=hidden_dim,
                output_dim=feature_dim,
                dropout=0.0,
            ).to(device)
            module.load_state_dict(state_dict)
            module.train()
            layer_transforms[layer_name] = module

    cross_attn = None
    if "cross_attn" in checkpoint:
        from utils.spatial_cross_attention import build_layer_adaptive_cross_attention

        config = checkpoint.get("cross_attn_config", {})
        cross_attn = build_layer_adaptive_cross_attention(
            layers=features_list,
            embed_dim=feature_dim,
            num_anchors=config.get("num_anchors", 4),
            dropout=config.get("dropout", 0.1),
            res_scale_init=config.get("res_scale_init", 0.01),
        ).to(device)
        cross_attn.load_state_dict(checkpoint["cross_attn"])
        cross_attn.train()

    trainable_parameters = [
        model.visual.anomaly_token,
        model.visual.normal_token,
    ]
    if layer_transforms:
        trainable_parameters.extend(layer_transforms.parameters())
    if cross_attn is not None:
        trainable_parameters.extend(cross_attn.parameters())

    anchor_state = {
        "anomaly_token": model.visual.anomaly_token.detach().clone(),
        "normal_token": model.visual.normal_token.detach().clone(),
        "layer_transforms": {
            name: {key: value.detach().clone() for key, value in module.state_dict().items()}
            for name, module in layer_transforms.items()
        },
        "cross_attn": (
            {key: value.detach().clone() for key, value in cross_attn.state_dict().items()}
            if cross_attn is not None
            else None
        ),
    }

    return {
        "checkpoint": checkpoint,
        "model": model,
        "layer_transforms": layer_transforms,
        "cross_attn": cross_attn,
        "device": device,
        "backbone": backbone,
        "image_size": image_size,
        "features_list": features_list,
        "trainable_parameters": trainable_parameters,
        "anchor_state": anchor_state,
    }


def forward_anomaly_scores(bundle, images: torch.Tensor):
    model = bundle["model"]
    layer_transforms = bundle["layer_transforms"]
    cross_attn = bundle["cross_attn"]
    features_list = bundle["features_list"]
    image_size = bundle["image_size"]

    vision_output = model.encode_image(images, features_list)
    anomaly_features = vision_output["anomaly_features"]
    normal_features = vision_output["normal_features"]
    patch_tokens = vision_output["patch_tokens"]
    patch_start_idx = vision_output["patch_start_idx"]

    patch_features_list = [pt[:, patch_start_idx:, :] for pt in patch_tokens]
    if cross_attn is not None:
        adapted_list = cross_attn(anomaly_features, normal_features, patch_features_list, features_list)
        anomaly_features_list = [item["anomaly"] for item in adapted_list]
        normal_features_list = [item["normal"] for item in adapted_list]
    else:
        anomaly_features_list = [anomaly_features] * len(patch_tokens)
        normal_features_list = [normal_features] * len(patch_tokens)

    anomaly_maps = []
    for layer_idx, patch_feature in enumerate(patch_tokens):
        anomaly_feat_norm = F.normalize(anomaly_features_list[layer_idx], dim=1, eps=1e-8)
        normal_feat_norm = F.normalize(normal_features_list[layer_idx], dim=1, eps=1e-8)

        transform_key = f"layer_{features_list[layer_idx]}"
        if transform_key in layer_transforms:
            batch_size, num_patches, feat_dim = patch_feature.shape
            patch_feature = layer_transforms[transform_key](patch_feature.view(-1, feat_dim)).view(
                batch_size, num_patches, feat_dim
            )

        anomaly_map = generate_anomaly_map_from_tokens(
            anomaly_feat_norm,
            normal_feat_norm,
            patch_feature[:, patch_start_idx:, :],
            image_size,
        )
        anomaly_maps.append(anomaly_map)

    final_anomaly_map = torch.stack(anomaly_maps).sum(dim=0)
    scores = reduce_anomaly_map(
        final_anomaly_map,
        mode="topk_mean",
        topk_ratio=DEFAULT_TOPK_RATIO,
    )

    return {
        "scores": scores,
        "anomaly_map": final_anomaly_map,
        "anomaly_features": anomaly_features_list[-1],
        "normal_features": normal_features_list[-1],
    }


def reduce_scores_with_gaussian(anomaly_map: torch.Tensor, sigma: float):
    if sigma <= 0:
        return reduce_anomaly_map(anomaly_map, mode="topk_mean", topk_ratio=DEFAULT_TOPK_RATIO)

    smoothed_maps = []
    for sample_map in anomaly_map.detach().cpu():
        filtered = gaussian_filter(sample_map.numpy(), sigma=sigma)
        smoothed_maps.append(torch.from_numpy(filtered))
    smoothed_maps = torch.stack(smoothed_maps, dim=0)
    return reduce_anomaly_map(smoothed_maps, mode="topk_mean", topk_ratio=DEFAULT_TOPK_RATIO)


def compute_anchor_loss(bundle) -> torch.Tensor:
    device = bundle["device"]
    loss = torch.tensor(0.0, device=device)
    term_count = 0

    anomaly_token = bundle["model"].visual.anomaly_token
    normal_token = bundle["model"].visual.normal_token
    loss = loss + F.mse_loss(anomaly_token, bundle["anchor_state"]["anomaly_token"].to(device))
    loss = loss + F.mse_loss(normal_token, bundle["anchor_state"]["normal_token"].to(device))
    term_count += 2

    for name, module in bundle["layer_transforms"].items():
        reference_state = bundle["anchor_state"]["layer_transforms"][name]
        current_state = module.state_dict()
        for key, value in current_state.items():
            loss = loss + F.mse_loss(value, reference_state[key].to(device))
            term_count += 1

    if bundle["cross_attn"] is not None:
        reference_state = bundle["anchor_state"]["cross_attn"]
        current_state = bundle["cross_attn"].state_dict()
        for key, value in current_state.items():
            loss = loss + F.mse_loss(value, reference_state[key].to(device))
            term_count += 1

    return loss / max(1, term_count)


def compute_margin_loss(scores: torch.Tensor, labels: torch.Tensor, positive_margin: float, decision_threshold: float):
    losses = []

    positive_scores = scores[labels > 0.5]
    if positive_scores.numel() > 0:
        losses.append(torch.relu(float(positive_margin) - positive_scores).mean())

    negative_scores = scores[labels <= 0.5]
    if negative_scores.numel() > 0:
        losses.append(torch.relu(negative_scores - float(decision_threshold)).mean())

    if not losses:
        return scores.new_tensor(0.0)

    return sum(losses) / len(losses)


def compute_epoch_metrics(scores: List[float], labels: List[float], decision_threshold: float):
    if not scores:
        return {
            "mean_score": 0.0,
            "mean_probability": 0.0,
            "positive_rate": 0.0,
            "accuracy": None,
            "num_samples": 0,
        }

    scores_np = np.asarray(scores, dtype=np.float32)
    labels_np = np.asarray(labels, dtype=np.float32)
    preds_np = (scores_np >= float(decision_threshold)).astype(np.float32)

    accuracy = None
    if len(np.unique(labels_np)) > 1:
        accuracy = float((preds_np == labels_np).mean())

    return {
        "mean_score": float(scores_np.mean()),
        "mean_probability": float((1.0 / (1.0 + np.exp(-scores_np))).mean()),
        "positive_rate": float(preds_np.mean()),
        "accuracy": accuracy,
        "num_samples": int(scores_np.shape[0]),
    }


def save_finetuned_checkpoint(bundle, output_path: Path, args, epoch: int, extra_metrics: Dict):
    output_path.parent.mkdir(parents=True, exist_ok=True)

    checkpoint = deepcopy(bundle["checkpoint"])
    checkpoint["anomaly_token"] = bundle["model"].visual.anomaly_token.detach().cpu()
    checkpoint["normal_token"] = bundle["model"].visual.normal_token.detach().cpu()

    if bundle["layer_transforms"]:
        checkpoint["layer_transforms"] = {
            name: {key: value.detach().cpu() for key, value in module.state_dict().items()}
            for name, module in bundle["layer_transforms"].items()
        }

    if bundle["cross_attn"] is not None:
        checkpoint["cross_attn"] = {
            key: value.detach().cpu() for key, value in bundle["cross_attn"].state_dict().items()
        }

    checkpoint["finetune_info"] = {
        "task": "bottle_positive_only_adaptation",
        "epoch": epoch,
        "decision_threshold": args.decision_threshold,
        "sigma": args.sigma,
        "source_metadata": str(args.metadata_path),
        "extra_metrics": extra_metrics,
        "note": (
            "This checkpoint was finetuned on anomaly-only bottle-cap images. "
            "It is intended for image-level normal/anomaly classification and anomaly localization inference."
        ),
    }

    torch.save(checkpoint, output_path)


def evaluate(bundle, dataloader, args):
    model = bundle["model"]
    cross_attn = bundle["cross_attn"]
    layer_transforms = bundle["layer_transforms"]

    model.eval()
    if cross_attn is not None:
        cross_attn.eval()
    layer_transforms.eval()

    losses = []
    scores = []
    labels = []

    contrastive_loss_fn = ContrastiveLoss(temperature=0.1, margin=0.5)
    amp_enabled = args.amp_enabled and bundle["device"].startswith("cuda")

    total_steps = len(dataloader)
    if args.max_val_steps:
        total_steps = min(total_steps, args.max_val_steps)
    progress = tqdm(dataloader, total=total_steps, desc="Validation", leave=False, mininterval=1.0)

    with torch.no_grad():
        for step_idx, batch in enumerate(progress, start=1):
            images = batch["image"].to(bundle["device"], non_blocking=True)
            batch_labels = batch["label"].to(bundle["device"], non_blocking=True)

            with autocast(enabled=amp_enabled):
                forward_output = forward_anomaly_scores(bundle, images)
                raw_scores = forward_output["scores"]
                eval_scores = reduce_scores_with_gaussian(
                    forward_output["anomaly_map"], sigma=args.sigma
                ).to(bundle["device"])

                classification_loss = F.binary_cross_entropy_with_logits(raw_scores, batch_labels)
                margin_loss = compute_margin_loss(
                    raw_scores,
                    batch_labels,
                    positive_margin=args.positive_margin,
                    decision_threshold=args.decision_threshold,
                )
                token_relation_loss = contrastive_loss_fn(
                    F.normalize(forward_output["anomaly_features"], dim=1, eps=1e-8),
                    F.normalize(forward_output["normal_features"], dim=1, eps=1e-8),
                )
                anchor_loss = compute_anchor_loss(bundle)
                total_loss = (
                    classification_loss
                    + args.margin_loss_weight * margin_loss
                    + args.token_relation_weight * token_relation_loss
                    + args.anchor_loss_weight * anchor_loss
                )

            losses.append(float(total_loss.item()))
            scores.extend(eval_scores.detach().cpu().tolist())
            labels.extend(batch_labels.detach().cpu().tolist())
            progress.set_postfix(loss=f"{total_loss.item():.4f}", score=f"{raw_scores.mean().item():.3f}")

            if args.max_val_steps and step_idx >= args.max_val_steps:
                break

    metrics = compute_epoch_metrics(scores, labels, args.decision_threshold)
    metrics["loss"] = float(np.mean(losses)) if losses else 0.0
    return metrics


def train_one_epoch(bundle, dataloader, optimizer, scaler, args):
    model = bundle["model"]
    cross_attn = bundle["cross_attn"]
    layer_transforms = bundle["layer_transforms"]

    model.train()
    if cross_attn is not None:
        cross_attn.train()
    layer_transforms.train()

    contrastive_loss_fn = ContrastiveLoss(temperature=0.1, margin=0.5)
    losses = []
    scores = []
    labels = []
    amp_enabled = args.amp_enabled and bundle["device"].startswith("cuda")

    total_steps = len(dataloader)
    if args.max_train_steps:
        total_steps = min(total_steps, args.max_train_steps)
    progress = tqdm(dataloader, total=total_steps, desc="Training", leave=False, mininterval=1.0)
    step_start_time = time.perf_counter()

    for step_idx, batch in enumerate(progress, start=1):
        images = batch["image"].to(bundle["device"], non_blocking=True)
        batch_labels = batch["label"].to(bundle["device"], non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with autocast(enabled=amp_enabled):
            forward_output = forward_anomaly_scores(bundle, images)
            raw_scores = forward_output["scores"]

            classification_loss = F.binary_cross_entropy_with_logits(raw_scores, batch_labels)
            margin_loss = compute_margin_loss(
                raw_scores,
                batch_labels,
                positive_margin=args.positive_margin,
                decision_threshold=args.decision_threshold,
            )
            token_relation_loss = contrastive_loss_fn(
                F.normalize(forward_output["anomaly_features"], dim=1, eps=1e-8),
                F.normalize(forward_output["normal_features"], dim=1, eps=1e-8),
            )
            anchor_loss = compute_anchor_loss(bundle)

            total_loss = (
                classification_loss
                + args.margin_loss_weight * margin_loss
                + args.token_relation_weight * token_relation_loss
                + args.anchor_loss_weight * anchor_loss
            )

        if amp_enabled:
            scaler.scale(total_loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            total_loss.backward()
            optimizer.step()

        losses.append(float(total_loss.item()))
        scores.extend(raw_scores.detach().cpu().tolist())
        labels.extend(batch_labels.detach().cpu().tolist())
        elapsed = time.perf_counter() - step_start_time
        images_per_sec = images.shape[0] / max(elapsed, 1e-6)
        step_start_time = time.perf_counter()
        progress.set_postfix(
            loss=f"{total_loss.item():.4f}",
            score=f"{raw_scores.mean().item():.3f}",
            ips=f"{images_per_sec:.2f}",
        )

        if args.max_train_steps and step_idx >= args.max_train_steps:
            break

    metrics = compute_epoch_metrics(scores, labels, args.decision_threshold)
    metrics["loss"] = float(np.mean(losses)) if losses else 0.0
    return metrics


def main():
    args = parse_args()
    project_root = resolve_project_root()

    args.metadata_path = resolve_path(project_root, args.metadata_path)
    args.checkpoint_path = resolve_path(project_root, args.checkpoint_path)
    args.output_dir = resolve_path(project_root, args.output_dir)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    set_seed(args.seed)
    torch.set_float32_matmul_precision("high")

    train_entries, val_entries, stats = load_metadata(args.metadata_path)
    if not train_entries:
        raise RuntimeError("Training split is empty.")
    if not val_entries:
        raise RuntimeError("Validation split is empty.")

    device = resolve_device(args.requested_device)
    args.amp_enabled = device.startswith("cuda") and not args.disable_amp
    if device.startswith("cuda"):
        torch.backends.cudnn.benchmark = True
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
    bundle = load_visualad_bundle(args.checkpoint_path, device=device)

    effective_num_workers = 0 if args.cache_images else args.num_workers
    train_dataset = BottleBinaryDataset(
        train_entries,
        image_size=bundle["image_size"],
        cache_images=args.cache_images,
        cache_dtype=args.cache_dtype,
        desc="train",
    )
    val_dataset = BottleBinaryDataset(
        val_entries,
        image_size=bundle["image_size"],
        cache_images=args.cache_images,
        cache_dtype=args.cache_dtype,
        desc="val",
    )

    train_loader_kwargs = dict(
        dataset=train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=effective_num_workers,
        pin_memory=device.startswith("cuda"),
    )
    val_loader_kwargs = dict(
        dataset=val_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=effective_num_workers,
        pin_memory=device.startswith("cuda"),
    )
    if effective_num_workers > 0:
        train_loader_kwargs["persistent_workers"] = True
        val_loader_kwargs["persistent_workers"] = True
        train_loader_kwargs["prefetch_factor"] = args.prefetch_factor
        val_loader_kwargs["prefetch_factor"] = args.prefetch_factor

    train_loader = DataLoader(**train_loader_kwargs)
    val_loader = DataLoader(**val_loader_kwargs)

    optimizer = torch.optim.AdamW(
        bundle["trainable_parameters"],
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )
    scaler = GradScaler(enabled=args.amp_enabled)

    history = []
    best_metric = None

    print("Starting bottle-cap finetuning")
    print(f"Device: {device}")
    print(f"Checkpoint: {args.checkpoint_path}")
    print(f"Metadata: {args.metadata_path}")
    print(f"Output dir: {args.output_dir}")
    print(f"Train images: {len(train_dataset)}")
    print(f"Val images: {len(val_dataset)}")
    print(f"Cache images: {args.cache_images}")
    print(f"Effective num_workers: {effective_num_workers}")
    print(f"AMP enabled: {args.amp_enabled}")
    if stats:
        print(f"Metadata note: {stats.get('note', 'n/a')}")

    for epoch in range(1, args.epochs + 1):
        print(f"\nEpoch {epoch:02d}/{args.epochs}")
        train_metrics = train_one_epoch(bundle, train_loader, optimizer, scaler, args)
        val_metrics = evaluate(bundle, val_loader, args)

        if val_metrics["accuracy"] is not None:
            current_metric = (val_metrics["accuracy"], val_metrics["mean_score"])
        else:
            current_metric = (val_metrics["mean_score"], val_metrics["positive_rate"])

        history_item = {
            "epoch": epoch,
            "train": train_metrics,
            "val": val_metrics,
        }
        history.append(history_item)

        history_path = args.output_dir / "history.json"
        history_path.write_text(json.dumps(history, indent=2, ensure_ascii=False) + "\n")

        print(
            f"Epoch {epoch:02d} | "
            f"train_loss={train_metrics['loss']:.4f} train_mean_score={train_metrics['mean_score']:.4f} | "
            f"val_loss={val_metrics['loss']:.4f} val_mean_score={val_metrics['mean_score']:.4f} "
            f"val_positive_rate={val_metrics['positive_rate']:.4f}"
        )

        save_finetuned_checkpoint(
            bundle,
            args.output_dir / "last_checkpoint.pth",
            args,
            epoch=epoch,
            extra_metrics=history_item,
        )

        if best_metric is None or current_metric > best_metric:
            best_metric = current_metric
            save_finetuned_checkpoint(
                bundle,
                args.output_dir / "best_checkpoint.pth",
                args,
                epoch=epoch,
                extra_metrics=history_item,
            )
            print(f"  Saved new best checkpoint at epoch {epoch}.")

    print("Finetuning completed.")
    print(f"Best checkpoint: {args.output_dir / 'best_checkpoint.pth'}")
    print(f"Last checkpoint: {args.output_dir / 'last_checkpoint.pth'}")


if __name__ == "__main__":
    main()
